# @package _global_
defaults:
  - override /trainer: base_trainer
  - override /data: base_data
  - override /hydra/launcher: submitit_slurm
  # - override /hydra/job_logging: default

trainer:
  platform: slurm
  results_dir: '/scratch/izar/sifringe/ImageDCM_Correlation/results'
  num_workers: 20
  batch_size: 512

data:
  raw_path: '/work/vita/datasets/MIT_moralMachine'

hydra:
  launcher:
      nodes: 1 # 2
      gpus_per_node: 1  # max 2
      cpus_per_task: 20
      tasks_per_node: 1
      # timeout_min: 240 # 4 hours (15 epochs can run in 2h30)
      timeout_min: 360 # 6 hours (account for transforms)
      partition: gpu
      qos: gpu
      submitit_folder: ${hydra.sweep.dir}/${hydra.sweep.subdir}
  mode: MULTIRUN


# To run on Scitas, multirun required to call the submitit launcher. Add & for background run:
# python run.py platform=scitas +exps=imCorr_masking &
