# @package _global_
defaults:
  - override /trainer: choice_corr
  - override /data: image_data

trainer:
  exp: '_composed'
  tabular_masking: 'remove'
  masked_tabular_list: ['Man','Barrier','Intervention']

  image_masking: 'composed'
  
data:
  controlled_mask_scale: 0.6

# Run this experiment with: python run.py +exps=imCorr_masking
