### !! Must run with data=image_data  ## Add assertion errors ?
defaults:
  - base_trainer

name: choice_detect_corr${trainer.exp}
type: choice_detect_corr
exp: '_${trainer.backbone_model}_${trainer.tab_model}'

epochs: 15
batch_size: 192
loss: ['cce','l2']

# For transfer learning
train_backbone: true
#[Res50, Res18, AlexNet]
backbone_model: Res18
tab_model: mnl
im_model: 'choice_w_detection'

fuse_image_detection_labels: true


# Batch and data
drop_last: true
shuffle: false
num_workers: 6
cuda: true

param:
  weight_decay: 0
  lr: 0.0001
  utility_lr_multiplier: 20

log:
  check_every_n_epoch: 1
  every_n_iter: 150

eval:
  beta_r_stats: true
