### !! Must run with data=image_data
defaults:
  - base_trainer

name: choice_corr${trainer.exp}
type: imCorr
exp: '_${trainer.backbone_model}_${trainer.tab_model}'

epochs: 15
batch_size: 192
loss: ['cce']

# For transfer learning
train_backbone: true
#[Res50, Res18, AlexNet]
backbone_model: Res18
tab_model: mnl
im_model: im_choice

# Batch and data
drop_last: true
shuffle: false
num_workers: 6
cuda: true

param:
  weight_decay: 0
  lr: 0.0001
  utility_lr_multiplier: 20

log:
  every_n_iter: 150
  check_every_n_epoch: 1
