### !! Must run with data=image_data  ## Add assertion errors ?
defaults:
  - choice_detect_corr

name: gain${trainer.exp}
type: gain

loss: ['l2', 'detect_masked']
im_model: res18

batch_size: 72

gainParam:
  # soft mask parameters during sigmoid, threshold and scale
  sigma: 0.25
  omega: 100
  use_gradcam: true